server:
  port: 8081

spring:
  application:
    name: skills
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5441/postgres
    username: postgres
    password:

eureka:
  client:
    registry-fetch-interval-seconds: 10
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  instance:
    appname: skills
    instance-id: skills:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true